name: juncBase-dependencies
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=2.7
  - biopython
  - pysam
  - r-base
  - rpy2
  - r-ggplot2
  - matplotlib
  - bioconductor-limma
  - bioconductor-DirichletMultinomial
  - sqlite3